### ISSUE TITLE
Implement SortAscending method of the singly linked list

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/go-playground#18]
Implement SortAscending method of the singly linked list data structure.
https://github.com/radlinskii/go-playground/blob/a43c4af9991428b839a386c9185351bc02e5c7b4/datastructures/lists/singlylinked/singly_linked.go#L233

Test it using ExampleSortAscending using Print method, working example:
https://github.com/radlinskii/go-playground/blob/a43c4af9991428b839a386c9185351bc02e5c7b4/datastructures/lists/singlylinked/singlylinked_test.go#L259

**Comment by dreamer-89** [comment]
@radlinskii : Please assign this issue to me. I am interested to work on this.

**Comment by dreamer-89** [comment]
@radlinskii : Please review and merge: https://github.com/radlinskii/go-playground/pull/22
